name: platform_maps_flutter_macos_example
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  # The app-facing widget/package you already use:
  platform_maps_flutter: ^2.0.0-beta

  # Your macOS implementation (this repo)
  platform_maps_flutter_macos:
    path: ..

  # Platform interface dependency
  platform_maps_flutter_platform_interface: ^1.0.0-beta.1

  # Your MapKit plugin (adjust the relative path to where it lives)
  flutter_macos_maps: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
