name: platform_maps_flutter_macos
description: macOS implementation of platform_maps_flutter using MapKit via flutter_macos_maps.
version: 0.1.0
homepage: https://github.com/chrisfranko/platform_maps_flutter_macos
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: platform_maps_flutter
    platforms:
      macos:
        dartPluginClass: PlatformMapsFlutterMacOS
        file: platform_maps_flutter_macos.dart

dependencies:
  flutter:
    sdk: flutter
  platform_maps_flutter_platform_interface: ^1.0.0-beta.1
  flutter_macos_maps: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
