name: platform_maps_flutter_macos
description: macOS implementation of platform_maps_flutter using MapKit via flutter_macos_maps.
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_maps_flutter_platform_interface: ^1.0.0-beta
  flutter_macos_maps: 
    git: 
      url: https://github.com/chrisfranko/flutter_macos_maps.git
      ref: main

flutter:
  plugin:
    implements: platform_maps_flutter
    platforms:
      macos:
        dartPluginClass: PlatformMapsFlutterMacOS
